/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bottom1: typeof import('./src/components/Nav/bottom1.vue')['default']
    Bread: typeof import('./src/components/coms/Bread.vue')['default']
    Button: typeof import('./src/components/coms/Button.vue')['default']
    Dir: typeof import('./src/components/ref/Dir.vue')['default']
    Expan: typeof import('./src/components/coms/Expan.vue')['default']
    Fbutton: typeof import('./src/components/coms/Fbutton.vue')['default']
    Footer: typeof import('./src/components/coms/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/coms/HelloWorld.vue')['default']
    Home: typeof import('./src/components/coms/Home.vue')['default']
    Layout1: typeof import('./src/components/layout/Layout1.vue')['default']
    Layout2: typeof import('./src/components/layout/Layout2.vue')['default']
    Layout3: typeof import('./src/components/layout/Layout3.vue')['default']
    Layout4: typeof import('./src/components/layout/Layout4.vue')['default']
    LayoutOne: typeof import('./src/components/layout/LayoutOne.vue')['default']
    LayoutTwo: typeof import('./src/components/layout/LayoutTwo.vue')['default']
    Nav1: typeof import('./src/components/Nav/Nav1.vue')['default']
    Nav2: typeof import('./src/components/Nav/Nav2.vue')['default']
    Nav3: typeof import('./src/components/Nav/Nav3.vue')['default']
    Nav4: typeof import('./src/components/Nav/Nav4.vue')['default']
    Nav5: typeof import('./src/components/Nav/Nav5.vue')['default']
    Page: typeof import('./src/components/coms/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/coms/Tabs.vue')['default']
    Taps: typeof import('./src/components/coms/Taps.vue')['default']
    Tooltip: typeof import('./src/components/coms/Tooltip.vue')['default']
    Tooltips: typeof import('./src/components/coms/Tooltips.vue')['default']
  }
}
