/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bottom1: typeof import('./src/components/Nav/bottom1.vue')['default']
    Bread: typeof import('./src/components/coms/Bread.vue')['default']
    Button: typeof import('./src/components/coms/Button.vue')['default']
    Cg: typeof import('./src/components/coms/Cg.vue')['default']
    Comp: typeof import('./src/components/ref/Comp.vue')['default']
    Cslide: typeof import('./src/components/coms/Cslide.vue')['default']
    Dir: typeof import('./src/components/ref/Dir.vue')['default']
    Events: typeof import('./src/components/ref/Events.vue')['default']
    Expan: typeof import('./src/components/coms/Expan.vue')['default']
    Fbutton: typeof import('./src/components/coms/Fbutton.vue')['default']
    Footer: typeof import('./src/components/coms/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/coms/HelloWorld.vue')['default']
    Home: typeof import('./src/components/coms/Home.vue')['default']
    Ig: typeof import('./src/components/coms/Ig.vue')['default']
    Layout1: typeof import('./src/components/layout/Layout1.vue')['default']
    Layout2: typeof import('./src/components/layout/Layout2.vue')['default']
    Layout3: typeof import('./src/components/layout/Layout3.vue')['default']
    Layout4: typeof import('./src/components/layout/Layout4.vue')['default']
    LayoutOne: typeof import('./src/components/layout/LayoutOne.vue')['default']
    LayoutTwo: typeof import('./src/components/layout/LayoutTwo.vue')['default']
    Met: typeof import('./src/components/ref/Met.vue')['default']
    MEt: typeof import('./src/components/ref/MEt.vue')['default']
    Nav1: typeof import('./src/components/Nav/Nav1.vue')['default']
    Nav2: typeof import('./src/components/Nav/Nav2.vue')['default']
    Nav3: typeof import('./src/components/Nav/Nav3.vue')['default']
    Nav4: typeof import('./src/components/Nav/Nav4.vue')['default']
    Nav5: typeof import('./src/components/Nav/Nav5.vue')['default']
    Otpin: typeof import('./src/components/coms/Otpin.vue')['default']
    Page: typeof import('./src/components/coms/Page.vue')['default']
    Radiobtn: typeof import('./src/components/coms/Radiobtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rs: typeof import('./src/components/coms/Rs.vue')['default']
    Sgr: typeof import('./src/components/coms/Sgr.vue')['default']
    Ste: typeof import('./src/components/coms/Ste.vue')['default']
    Swit: typeof import('./src/components/coms/Swit.vue')['default']
    Ta: typeof import('./src/components/coms/Ta.vue')['default']
    Tabs: typeof import('./src/components/coms/Tabs.vue')['default']
    Taps: typeof import('./src/components/coms/Taps.vue')['default']
    Tbtn: typeof import('./src/components/coms/Tbtn.vue')['default']
    Tf: typeof import('./src/components/coms/Tf.vue')['default']
    Tooltip: typeof import('./src/components/coms/Tooltip.vue')['default']
    Tooltips: typeof import('./src/components/coms/Tooltips.vue')['default']
    Vmodel: typeof import('./src/components/ref/Vmodel.vue')['default']
    Watc: typeof import('./src/components/ref/Watc.vue')['default']
    Win: typeof import('./src/components/coms/Win.vue')['default']
  }
}
